apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: identity-api-ingress
  namespace: identity
spec:
  podSelector:
    matchLabels:
      app: identity-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: chatbot
          podSelector:
            matchLabels:
              app: chatbot-backend
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: chatbot
          podSelector:
            matchLabels:
              app: chatbot-frontend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb-ingress
  namespace: identity
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: identity-api
      ports:
        - protocol: TCP
          port: 27017
