apiVersion: v1
kind: Service
metadata:
  name: chatbot-mongodb
  namespace: chatbot
  labels:
    app: chatbot-mongodb
spec:
  selector:
    app: chatbot-mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chatbot-mongodb
  namespace: chatbot
spec:
  serviceName: chatbot-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-mongodb
  template:
    metadata:
      labels:
        app: chatbot-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: chatbot
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: mongo-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: mongo-password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
